import { Unbounded } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  display: "swap", // Додає стабільне завантаження шрифту
});

export const metadata = {
  title: "WebHjerte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<body className={`${unbounded.variable} antialiased`} suppressHydrationWarning> <Header/>{children}<Footer/>
      </body>
    </html>
  );
}
